export const EVENTS = {
  // Room Events
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_DELETED: 'ROOM_DELETED',
  ROOM_STATUS_CHANGED: 'ROOM_STATUS_CHANGED',

  // Request Events
  REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',

  // Chat Events
  CHAT_OPENED: 'CHAT_OPENED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
} as const;
